HolmesCrafts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("core.urls", "core"), namespace = "core"), ),
    path("", include(("accounts.urls", "accounts"), namespace = "accounts"), ),
    path("", include(("catalog.urls", "catalog"), namespace = "catalog"), ),
    path("basket/", include(("cart.urls", "cart"), namespace = "cart"), ),
    path("payments/", include(("payments.urls", "payments"), namespace="payments"), ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.BasketView.as_view(), name="basket"),
    path("remove/", views.BasketRemoveView.as_view(), name="basket_remove"),
]

catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"

urlpatterns = [
    path("notebooks/", views.NotebooksView.as_view(), name="notebooks"),
    path("cards/<slug:slug>/", views.CardsView.as_view(), name="cards"),
    path("notebooks/<slug:slug>/", views.NotebookShopPageView.as_view(), name="notebook_shop_page"),
    path("cards/<slug:page_slug>/<slug:slug>/", views.CardShopPageView.as_view(), name="card_shop_page")
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home_page")
]

core/models.py
from django.db import models


class Navbar(models.Model):
    page_name = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    is_card = models.BooleanField()
    slug = models.SlugField(default="", blank=True, null=False, db_index=True)
    order = models.PositiveIntegerField(default=0, editable=False)

    def __str__(self):
        return self.page_name

    class Meta:
        ordering = ["order"]
        verbose_name_plural = "Navbar pages"   

core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

from catalog.services import get_featured

class HomeView(TemplateView):
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_featured())
        context["current_page"] = "HOME"
        return context

core/templates/core/index.html
{% extends "base.html" %}

{% load static %}

{% block title %} Home | {{ block.super }} {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'core/styles/index.css' %}">
{% endblock %}

{% block content %}
<a class="pageLink" href="{% url 'catalog:notebooks' %}">
    <div class="Sections" id="Notebooks">
        <h2 class="PageName">Notebooks</h2>
        <div class="egcards">
            <img class="leftfeatured" src="{{ notebooks.0.images.front_cover.url }}" alt="{{ notebooks.0.name }}">
            <img class="midfeatured" src="{{ notebooks.1.images.front_cover.url }}" alt="{{ notebooks.1.name }}">
            <img class="rightfeatured" src="{{ notebooks.2.images.front_cover.url }}" alt="{{ notebooks.2.name }}">
        </div>
    </div>
</a>
<a class="pageLink" href="{% url 'catalog:cards' 'birthday' %}">
    <div class="Sections" id="BirthdayCards">
        <h2 class="PageName">Birthday Cards</h2>
        <div class="egcards">
            <img class="leftfeatured" src="{{ birthday_cards.0.images.tall_img.url }}" alt="{{ birthday_cards.0.name }}">
            <img class="midfeatured" src="{{ birthday_cards.1.images.tall_img.url }}" alt="{{ birthday_cards.1.name }}">
            <img class="rightfeatured" src="{{ birthday_cards.2.images.tall_img.url }}" alt="{{ birthday_cards.2.name }}">
        </div>
    </div>
</a>
<a class="pageLink" href="{% url 'catalog:cards' 'wedding-and-anniversary' %}">
    <div class="Sections" id="WeddingCards">
        <h2 class="PageName">Wedding &amp; Anniversary Cards</h2>
        <div class="egcards">
            <img class="leftfeatured" src="{{ wedding_cards.0.images.tall_img.url }}" alt="{{ wedding_cards.0.name }}">
            <img class="midfeatured" src="{{ wedding_cards.1.images.tall_img.url }}" alt="{{ wedding_cards.1.name }}">
            <img class="rightfeatured" src="{{ wedding_cards.2.images.tall_img.url }}" alt="{{ wedding_cards.2.name }}">
        </div>
    </div>
</a>
<a class="pageLink" href="{% url 'catalog:cards' 'seasonal' %}">
    <div class="Sections" id="SeasonalCards">
        <h2 class="PageName">Seasonal Cards</h2>
        <div class="egcards">
            <img class="leftfeatured" src="{{ seasonal_cards.0.images.tall_img.url }}" alt="{{ seasonal_cards.0.name }}">
            <img class="midfeatured" src="{{ seasonal_cards.1.images.tall_img.url }}" alt="{{ seasonal_cards.1.name }}">
            <img class="rightfeatured" src="{{ seasonal_cards.2.images.tall_img.url }}" alt="{{ seasonal_cards.2.name }}">
        </div>
    </div>
</a>
<a class="pageLink" href="{% url 'catalog:cards' 'special-occasion' %}">
    <div class="Sections" id="SpecialCards">
        <h2 class="PageName">Cards for Special Occasions</h2>
        <div class="egcards">
            <img class="leftfeatured" src="{{ special_cards.1.images.tall_img.url }}" alt="{{ special_cards.1.name }}">
            <img class="midfeatured" src="{{ special_cards.0.images.tall_img.url }}" alt="{{ special_cards.0.name }}">
            <img class="rightfeatured" src="" alt="">
        </div>
    </div>
</a>
<a class="pageLink" href="{% url 'catalog:cards' 'other' %}">
    <div class="Sections" id="OtherCards">
        <h2 class="PageName">Other Cards</h2>
        <div class="egcards">
            <img class="leftfeatured" src="" alt="">
            <img class="midfeatured" src="" alt="">
            <img class="rightfeatured" src="" alt="">
        </div>
    </div>
</a>
{% endblock %}