HolmesCrafts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("core.urls", "core"), namespace = "core"), ),
    path("", include(("accounts.urls", "accounts"), namespace = "accounts"), ),
    path("", include(("catalog.urls", "catalog"), namespace = "catalog"), ),
    path("basket/", include(("cart.urls", "cart"), namespace = "cart"), ),
    path("payments/", include(("payments.urls", "payments"), namespace="payments"), ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.BasketView.as_view(), name="basket"),
    path("remove/", views.BasketRemoveView.as_view(), name="basket_remove"),
]

catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"

urlpatterns = [
    path("notebooks/", views.NotebooksView.as_view(), name="notebooks"),
    path("cards/<slug:slug>/", views.CardsView.as_view(), name="cards"),
    path("notebooks/<slug:slug>/", views.NotebookShopPageView.as_view(), name="notebook_shop_page"),
    path("cards/<slug:page_slug>/<slug:slug>/", views.CardShopPageView.as_view(), name="card_shop_page")
]

catalog/models.py
from django.db import models
import os
import uuid
from datetime import datetime

from .mixins import OrderingMixin

def upload_to(instance, filename):
    
    app_name = instance._meta.app_label
    folder_name = instance.__class__.__name__.lower()
    
    
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4().hex}.{ext}"
    
    
    date_path = datetime.now().strftime("%Y/%m/%d")
    
    return os.path.join(app_name, folder_name, date_path, filename)

class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Size(OrderingMixin, models.Model):

    ORIENTATION = (
        ("portrait", "Portrait"),
        ("landscape", "Landscape")
    )

    name = models.CharField(max_length=20)
    orientation = models.CharField(max_length=10, choices=ORIENTATION, default="portrait", null=True, blank=True)

    def __str__(self):
        return f"{self.name} - {self.orientation}"
    
class ProductType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class PriceGroup(OrderingMixin, models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.product_type} - ({self.size}) - £{self.price}"
    
class Product(OrderingMixin, models.Model):
    name = models.CharField(max_length=100, default="")
    price_group = models.ForeignKey(PriceGroup, on_delete=models.PROTECT, related_name="products")
    slug = models.SlugField(default="", blank=True, null=False, db_index=True)
    code = models.CharField(max_length=20, null=True, unique=True)
    is_featured = models.BooleanField(default=False)
    in_store = models.BooleanField(default=True)
    has_variants = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="products", blank=True)

    def __str__(self):
        return f"{self.name} ({self.code})"

    @property
    def price(self):
        return self.price_group.price

    @property
    def size(self):
        return self.price_group.size   
    



class Notebook(Product):
    theme = models.CharField(max_length=100)
    page_img = models.CharField(max_length=100)
    front_img = models.CharField(max_length=100)


class NotebookImg(models.Model):
    notebook = models.OneToOneField(Notebook, on_delete=models.CASCADE, related_name="images")
    open_cover = models.ImageField(upload_to=upload_to)
    front_cover = models.ImageField(upload_to=upload_to)
    inside_front = models.ImageField(upload_to=upload_to)
    inside_back = models.ImageField(upload_to=upload_to)
    middle = models.ImageField(upload_to=upload_to)

    def __str__(self):
        return f"{self.notebook} images"
    
    class Meta:
        verbose_name_plural = "Notebook images"

class CardType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Card(Product):
    card_type = models.ForeignKey(CardType, on_delete=models.PROTECT, related_name="cards")

class CardInsert(models.Model):
    card_type = models.ForeignKey(CardType, on_delete=models.PROTECT, related_name="card_inserts")
    size = models.ForeignKey(Size, on_delete=models.PROTECT)
    message = models.CharField(max_length=100)
    picture = models.CharField(max_length=100)
    img = models.ImageField(upload_to=upload_to)

    def __str__(self):
        return f"{self.card_type} ({self.size.name}) - {self.picture} | {self.message}"
    

    
class CardImg(models.Model):
    card = models.OneToOneField(Card, on_delete=models.CASCADE, related_name="images")
    wide_img = models.ImageField(upload_to=upload_to, null=True, blank=True)
    tall_img = models.ImageField(upload_to=upload_to, null=True, blank=True)
    small_img = models.ImageField(upload_to=upload_to, null=True, blank=True)
    inside_img = models.ForeignKey(CardInsert, on_delete=models.SET_NULL, related_name="images", null=True, blank=True)

    def __str__(self):
        return f"{self.card} images"
    
    class Meta:
        verbose_name_plural = "Card images"

class CardVariant(OrderingMixin, models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE, related_name="variants")
    variant_name = models.CharField(max_length=100)
    variant_img = models.ImageField(upload_to=upload_to)

    def __str__(self):
        return f"{self.card} ({self.variant_name})"

    class Meta(OrderingMixin.Meta):
        verbose_name_plural = "Card variants"

catalog/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Card, Notebook
from core.models import Navbar

class NotebooksView(ListView):
    template_name = "catalog/notebooks.html"
    model = Notebook
    context_object_name = "notebooks"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_page"] = "NOTEBOOKS"
        return context
    
class CardsView(ListView):
    template_name = "catalog/cards.html"
    model = Card
    context_object_name = "cards"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_page"] = get_object_or_404(Navbar, slug=self.kwargs["slug"])
        return context
    
class NotebookShopPageView(DetailView):
    template_name = "catalog/notebook_shop_page.html" 
    model = Notebook 
    context_object_name = "notebook"

    
    def post(self, request):
        cart = request.session.get("cart", {})
        product_id = request.POST["product_id"]
        quantity = request.POST["quantity"]

        cart[product_id] = quantity

        request.session["cart"] = cart
    
class CardShopPageView(DetailView):
    template_name = "catalog/card_shop_page.html" 
    model = Card
    context_object_name = "card"
    
    def post(self, request):
        cart = request.session.get("cart", {})
        product_id = request.POST["product_id"]
        quantity = request.POST["quantity"]

        cart[product_id] = quantity

        request.session["cart"] = cart

catalog/templates/catalog/card_shop_page.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ card.name }} | {{ block.super }} {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'catalog/styles/card_shop_page.css' %}">
{% endblock %}

{% block content %}
<div class="shop_container">
    <div class="small_images">
        <button class="shop_img_button" onClick ="changeImg()"><img class="small_shop_img" id="wide_img" src="{{ card.images.wide_img.url }}"></button>
        <button class="shop_img_button" onClick ="changeImg()"><img class="small_shop_img" id="tall_img" src="{{ card.images.tall_img.url }}"></button>
        <button class="shop_img_button" onClick ="changeImg()"><img class="small_shop_img" id="small_img" src="{{ card.images.small_img.url }}"></button>
        {% if card.images.inside_img %}
        <button class="shop_img_button" id="small_img4" onClick ="changeImg()"><img class="small_shop_img" src="{{ card.images.inside_img.url }}"></button>
        {% endif %}
    </div>
    <div class = "shop_img_container">
        <img class="shop_img" id="shop_img" src="{{ card.images.wide_img.url }}">
    </div>
    <div class="item_details" id="item_details">
        <p class="shop_card_name">{{ card.name }}</p>
        <p class="shop_card_size">Size: {{ card.size.name }}</p>
        <p class="shop_card_price">Price: £{{ card.price }}</p>
        {% if card.has_variants %}
        <div class="color_var">
            <button class="color_var_btn" id="color_var_btn">Pick a Color Variant</button>
            <div class="color_var_dropdown">
                {% for variant in card.variants.all %}
                    <a onClick ='colorVar("{{ variant.variant_img.url }}", "{{variant.variant_name}}", "{{ card.name }}", "{{ card.code }}")'>{{ variant.variant_name }}</a>
                {% endfor %}
            </div>
       </div>
       {% endif %}
        {% if not card.has_variants %}
            <p class="quantity_name">Quantity</p>
            <form class="add_to_cart_form" action="{% url 'cart:basket' %}" method="POST">
                {% csrf_token %}
                <input id="quantity" type="number" min="0" value="0" name="quantity">
                <input type="hidden" value="{{ card.images.small_img.url }}" name="product_img">
                <input type="hidden" value="{{ card.name }}" name="product_name">
                <input type="hidden" value="{{ card.price }}" name="product_price">
                <input type="hidden" value="{{ card.code }}" name="product_code">
                <button class="add_to_basket" type="submit">Add to cart</button>
            </form>
        {% else %}
            <p class="quantity_name hidden" id="card_var_quantity">Quantity</p>
            <form class="hidden" id="card_var_form" action="{% url 'cart:basket' %}" method="POST">
                {% csrf_token %}
                <input id="quantity" type="number" min="0" value="0" name="quantity">
                <input id="card_var_img" type="hidden" value="{{ card.images.small_img.url }}"s name="product_img">
                <input id="card_var_name" type="hidden" value="{{ card.name }}" name="product_name">
                <input type="hidden" value="{{ card.price }}" name="product_price">
                <input id="card_var_code" type="hidden" value="{{ card.code }}" name="product_code">
                <button class="add_to_basket" type="submit">Add to cart</button>
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'catalog/scripts/shop_page.js' %}"></script>
{% endblock %}

catalog/templates/catalog/cards.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ current_page.page_name|title }} Cards | {{ block.super }} {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'catalog/styles/cards.css' %}">
{% endblock %}

{% block content %}
<h1 class="pageTitle">{{ current_page.page_name|title }} Cards</h1>
{% for card in cards %}
    {% if card.card_type.name == current_page.page_name|title %}
        {% if card.in_store %}
            <a class="pageLink" href="{% url 'catalog:card_shop_page' current_page.slug card.slug %}">
                <div class="cardInfo">
                    <img class="card" src="{{ card.images.tall_img.url }}" alt="{{ card.name }}">
                    <p class="info">{{ card.name }}</p>
                    <p class="info">Size: {{ card.size.name }}</p>
                    <p class="info">Price: £{{ card.price }}</p>
                </div>
            </a>
        {% endif %}
    {% endif %}
{% endfor %}
{% endblock %}

catalog/templates/catalog/notebook_shop_page.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{ notebook.name }} | {{ block.super }} {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'catalog/styles/notebook_shop_page.css' %}">
{% endblock %}

{% block content %}
<div class="shop_container">
    <div class="small_images">
        <button class="shop_img_button" id="small_img1" onClick ="changeImg()"><img class="small_shop_img" src="{{ notebook.images.front_cover.url }}"></button>
        <button class="shop_img_button" id="small_img2" onClick ="changeImg()"><img class="small_shop_img" src="{{ notebook.images.open_cover.url }}"></button>
        <button class="shop_img_button" id="small_img3" onClick ="changeImg()"><img class="small_shop_img" src="{{ notebook.images.inside_front.url }}"></button>
        <button class="shop_img_button" id="small_img4" onClick ="changeImg()"><img class="small_shop_img" src="{{ notebook.images.middle.url }}"></button>
        <button class="shop_img_button" id="small_img5" onClick ="changeImg()"><img class="small_shop_img" src="{{ notebook.images.inside_back.url }}"></button>
        <button class="shop_img_button" id="small_img6" onClick ="changeImg()"><img class="small_shop_img" src="{% static 'catalog/images/Open-back-cover.jpg' %}"></button>
        <button class="shop_img_button" id="small_img7" onClick ="changeImg()"><img class="small_shop_img" src="{% static 'catalog/images/Zoom-Middle.jpg' %}"></button>
    </div>
    <div class= "shop_img_container">
        <img class="shop_img" id="shop_img" src="{{ notebook.images.open_cover.url }}">
    </div>
    <div class="item_details">
        <p class="shop_notebook_name">{{ notebook.name }}</p>
        <p class="shop_notebook_size">Size: {{ notebook.size.name }}</p>
        <p class="shop_notebook_price">Price: &pound;{{ notebook.price }}</p>
        <ul class="notebook_specs">
            <li>A5 Notebook with {{ notebook.theme }} Theme</li>
            <li>60 Sheets of 80gsm lined paper</li>
            <li>120 Perforated pages <br>with {{ notebook.page_img }} in the bottom outside corner</li>
            <li>Front cover 250gsm card with {{ notebook.front_img }} on the front</li>
            <li>Back cover 250gsm with a Holmes Crafts logo</li>
            <li>150 micron clear PVC binding covers</li>
        </ul>
        
        <p class="quantity_name">Quantity</p>
        <form class="add_to_cart_form" action="{% url 'cart:basket' %}" method="POST">
            {% csrf_token %}
            <input id="quantity" type="number" min="0" value="0" name="quantity">
            <input type="hidden" value="{{ notebook.images.front_cover.url }}" name="product_img">
            <input type="hidden" value="{{ notebook.name }}" name="product_name">
            <input type="hidden" value="{{ notebook.price }}" name="product_price">
            <input type="hidden" value="{{ notebook.code }}" name="product_code">
            <button class="add_to_basket" type="submit">Add to cart</button>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'catalog/scripts/shop_page.js' %}"></script>
{% endblock %}

catalog/templates/catalog/notebooks.html
{% extends "base.html" %}
{% load static %}

{% block title %} Notebooks | {{ block.super }} {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'catalog/styles/notebooks.css' %}">
{% endblock %}

{% block content %}
<h1 class="pageTitle">Notebooks</h1>
{% for notebook in notebooks %}
    <a class="pageLink" href="{% url 'catalog:notebook_shop_page' notebook.slug %}">
        <div class="NotebookInfo">
            <img class="NotebookMain" src="{{ notebook.images.front_cover.url }}" alt="{{ notebook.name }}">
            <p class="Notebookinfo">{{ notebook.name }}</p>
            <p class="Notebookinfo">Size: {{ notebook.size.name }}</p>
            <p class="Notebookinfo">Price: &pound;{{ notebook.price }}</p>
        </div>
    </a>
    {% endfor %}
{% endblock %}